name: Build toolchain

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential binutils-for-build texinfo bison flex zlib1g-dev libgmp-dev dejagnu libmpc-dev

      - name: Run Bash Script
        run: |
          chmod +x ./build.sh
          bash ./build.sh
